doctrine:
  dbal:
    driver: pdo_mysql
    host: mysql_db
    port: 3306
    dbname: prueba_tecnica
    user: dangelo-aguilar
    password: bjadbeuygasjhuiheIUG7676567
    charset: utf8mb4

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Domain/User/Entity'
        prefix: 'App\Domain\User\Entity'
        alias: App